CREATE TABLE IF NOT EXISTS store
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME    VARCHAR(10)NOT NULL,
    PASSWORD    VARCHAR(10)NOT NULL,
    PRIMARY KEY(ID,USERNAME)
) DEFAULT CHARSET=UTF-8;
